[build]
builder = "nixpacks"

[deploy]
startCommand = "python mcp-bearer-token/mcp_starter.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Railway will automatically set PORT
# Add your environment variables in Railway dashboard:
# AUTH_TOKEN = "your-auth-token"
# MY_NUMBER = "your-number"
